### ISSUE TITLE
Error in compilation - simd v0.1.0

### ISSUE THREAD

**Issue by szagi3891** [zonyitoo/coio-rs#10] opened 2015-10-08 03:38 UTC
I tried to run this library and i got an error compilation :

    Compiling simd v0.1.0 (https://github.com/huonw/simd#be424212)
     Running `rustc /home/grzegorz/.cargo/git/checkouts/simd-2a4f7a7525648cf1/master/src/lib.rs --crate-name simd --crate-type lib -g -C metadata=8818301eefd37519 -C extra-filename=-8818301eefd37519 --out-dir /home/grzegorz/Pulpit/rust_server/coio-test/target/debug/deps --emit=dep-info,link -L dependency=/home/grzegorz/Pulpit/rust_server/coio-test/target/debug/deps -L dependency=/home/grzegorz/Pulpit/rust_server/coio-test/target/debug/deps -Awarnings`
/home/grzegorz/.cargo/git/checkouts/simd-2a4f7a7525648cf1/master/src/lib.rs:169:8: 169:28 error: invalid ABI: expected one of [cdecl, stdcall, fastcall, aapcs, win64, Rust, C, system, rust-intrinsic, rust-call], found `platform-intrinsic`
/home/grzegorz/.cargo/git/checkouts/simd-2a4f7a7525648cf1/master/src/lib.rs:169 extern "platform-intrinsic" {
                                                                                       ^~~~~~~~~~~~~~~~~~~~
/home/grzegorz/.cargo/git/checkouts/simd-2a4f7a7525648cf1/master/src/x86/sse2.rs:9:8: 9:28 error: invalid ABI: expected one of [cdecl, stdcall, fastcall, aapcs, win64, Rust, C, system, rust-intrinsic, rust-call], found `platform-intrinsic`
/home/grzegorz/.cargo/git/checkouts/simd-2a4f7a7525648cf1/master/src/x86/sse2.rs:9 extern "platform-intrinsic" {
                                                                                          ^~~~~~~~~~~~~~~~~~~~
/home/grzegorz/.cargo/git/checkouts/simd-2a4f7a7525648cf1/master/src/x86/sse2.rs:18:8: 18:28 error: invalid ABI: expected one of [cdecl, stdcall, fastcall, aapcs, win64, Rust, C, system, rust-intrinsic, rust-call], found `platform-intrinsic`
/home/grzegorz/.cargo/git/checkouts/simd-2a4f7a7525648cf1/master/src/x86/sse2.rs:18 extern "platform-intrinsic" {
                                                                                           ^~~~~~~~~~~~~~~~~~~~
/home/grzegorz/.cargo/git/checkouts/simd-2a4f7a7525648cf1/master/src/x86/sse3.rs:4:8: 4:28 error: invalid ABI: expected one of [cdecl, stdcall, fastcall, aapcs, win64, Rust, C, system, rust-intrinsic, rust-call], found `platform-intrinsic`
/home/grzegorz/.cargo/git/checkouts/simd-2a4f7a7525648cf1/master/src/x86/sse3.rs:4 extern "platform-intrinsic" {
                                                                                          ^~~~~~~~~~~~~~~~~~~~
/home/grzegorz/.cargo/git/checkouts/simd-2a4f7a7525648cf1/master/src/x86/ssse3.rs:10:8: 10:28 error: invalid ABI: expected one of [cdecl, stdcall, fastcall, aapcs, win64, Rust, C, system, rust-intrinsic, rust-call], found `platform-intrinsic`
/home/grzegorz/.cargo/git/checkouts/simd-2a4f7a7525648cf1/master/src/x86/ssse3.rs:10 extern "platform-intrinsic" {
                                                                                            ^~~~~~~~~~~~~~~~~~~~
/home/grzegorz/.cargo/git/checkouts/simd-2a4f7a7525648cf1/master/src/x86/sse4_1.rs:5:8: 5:28 error: invalid ABI: expected one of [cdecl, stdcall, fastcall, aapcs, win64, Rust, C, system, rust-intrinsic, rust-call], found `platform-intrinsic`
/home/grzegorz/.cargo/git/checkouts/simd-2a4f7a7525648cf1/master/src/x86/sse4_1.rs:5 extern "platform-intrinsic" {
                                                                                            ^~~~~~~~~~~~~~~~~~~~
/home/grzegorz/.cargo/git/checkouts/simd-2a4f7a7525648cf1/master/src/x86/sse4_2.rs:4:8: 4:28 error: invalid ABI: expected one of [cdecl, stdcall, fastcall, aapcs, win64, Rust, C, system, rust-intrinsic, rust-call], found `platform-intrinsic`
/home/grzegorz/.cargo/git/checkouts/simd-2a4f7a7525648cf1/master/src/x86/sse4_2.rs:4 extern "platform-intrinsic" {
                                                                                            ^~~~~~~~~~~~~~~~~~~~
/home/grzegorz/.cargo/git/checkouts/simd-2a4f7a7525648cf1/master/src/x86/avx.rs:12:8: 12:28 error: invalid ABI: expected one of [cdecl, stdcall, fastcall, aapcs, win64, Rust, C, system, rust-intrinsic, rust-call], found `platform-intrinsic`
/home/grzegorz/.cargo/git/checkouts/simd-2a4f7a7525648cf1/master/src/x86/avx.rs:12 extern "platform-intrinsic" {
                                                                                          ^~~~~~~~~~~~~~~~~~~~
/home/grzegorz/.cargo/git/checkouts/simd-2a4f7a7525648cf1/master/src/x86/avx2.rs:4:8: 4:28 error: invalid ABI: expected one of [cdecl, stdcall, fastcall, aapcs, win64, Rust, C, system, rust-intrinsic, rust-call], found `platform-intrinsic`
/home/grzegorz/.cargo/git/checkouts/simd-2a4f7a7525648cf1/master/src/x86/avx2.rs:4 extern "platform-intrinsic" {
                                                                                          ^~~~~~~~~~~~~~~~~~~~
/home/grzegorz/.cargo/git/checkouts/simd-2a4f7a7525648cf1/master/src/arm/neon.rs:37:8: 37:28 error: invalid ABI: expected one of [cdecl, stdcall, fastcall, aapcs, win64, Rust, C, system, rust-intrinsic, rust-call], found `platform-intrinsic`
/home/grzegorz/.cargo/git/checkouts/simd-2a4f7a7525648cf1/master/src/arm/neon.rs:37 extern "platform-intrinsic" {
                                                                                           ^~~~~~~~~~~~~~~~~~~~
/home/grzegorz/.cargo/git/checkouts/simd-2a4f7a7525648cf1/master/src/aarch64/neon.rs:38:8: 38:28 error: invalid ABI: expected one of [cdecl, stdcall, fastcall, aapcs, win64, Rust, C, system, rust-intrinsic, rust-call], found `platform-intrinsic`
/home/grzegorz/.cargo/git/checkouts/simd-2a4f7a7525648cf1/master/src/aarch64/neon.rs:38 extern "platform-intrinsic" {
                                                                                               ^~~~~~~~~~~~~~~~~~~~
error: aborting due to 11 previous errors

please help :)

**Comment by zonyitoo** [comment] 2015-10-08 09:42
It seems that you are using a 32bits system? I think you should ask the author of `simd` for help.

**Comment by szagi3891** [comment] 2015-10-11 20:15
Yes, i use 32bits system. 
I set up a new issue: https://github.com/huonw/simd/issues/12

I think this issue can be closed. Thanks.

**Comment by zonyitoo** [comment] 2015-10-12 01:19
Please use nightly to compile this crate.

**Comment by szagi3891** [comment] 2015-10-14 06:46
In this version work.

But.
I try run example from link : https://github.com/zonyitoo/coio-rs#tcp-echo-server
And i get an error with a memory violation :

Waiting for connection ...
Naruszenie ochrony pamięci

"Naruszenie ochrony pamięci" mean "Segfaulted".

**Comment by zonyitoo** [comment] 2015-10-14 06:53
That's weird. Please use the Tcp echo server in example. Try this

```
cargo run --example tcp-echo-server -- --bind 127.0.0.1:8000
```

**Comment by szagi3891** [comment] 2015-10-14 07:20
Output :

grzegorz@grzegorz:~/Pulpit/rust_server/coio-rs$ cargo run --example tcp-echo-server -- --bind 127.0.0.1:8000
     Running `target/debug/examples/tcp-echo-server --bind 127.0.0.1:8000`
An unknown error occurred

To learn more, run the command again with --verbose.

grzegorz@grzegorz:~/Pulpit/rust_server/coio-rs$ cargo run --verbose --example tcp-echo-server -- --bind 127.0.0.1:8000
       Fresh bytes v0.2.10 (https://github.com/carllerche/bytes?rev=7edb577d0a#7edb577d)
       Fresh cfg-if v0.1.0
       Fresh gcc v0.3.18
       Fresh regex-syntax v0.2.2
       Fresh strsim v0.4.0
       Fresh libc v0.1.10
       Fresh log v0.3.2
       Fresh rustc-serialize v0.3.16
       Fresh winapi-build v0.1.1
       Fresh num_cpus v0.2.6
       Fresh bitflags v0.3.2
       Fresh nix v0.4.0 (https://github.com/carllerche/nix-rust?rev=f37e45628e#f37e4562)
       Fresh ansi_term v0.6.3
       Fresh clap v1.4.5
       Fresh memchr v0.1.6
       Fresh aho-corasick v0.3.2
       Fresh regex v0.1.41
       Fresh env_logger v0.3.1
       Fresh clock_ticks v0.0.5
       Fresh winapi v0.2.4
       Fresh kernel32-sys v0.1.4
       Fresh time v0.1.32
       Fresh fs2 v0.1.0
       Fresh advapi32-sys v0.1.2
       Fresh rand v0.3.11
       Fresh num v0.1.27
       Fresh chrono v0.2.16
       Fresh deque v0.2.3
       Fresh memmap v0.2.1
       Fresh context v0.1.3 (https://github.com/zonyitoo/context-rs.git#53b0a486)
       Fresh slab v0.1.2
       Fresh ws2_32-sys v0.1.0
       Fresh net2 v0.2.15
       Fresh wio v0.1.0 (https://github.com/alexcrichton/wio#688efd23)
       Fresh mio v0.5.0-pre (https://github.com/carllerche/mio.git#629141ab)
       Fresh coio v0.1.3 (file:///home/grzegorz/Pulpit/rust_server/coio-rs)
     Running `target/debug/examples/tcp-echo-server --bind 127.0.0.1:8000`
Process didn't exit successfully: `target/debug/examples/tcp-echo-server --bind 127.0.0.1:8000` (signal: 11)

**Comment by zonyitoo** [comment] 2015-10-14 08:46
What's your environment? x86 or x86_64? Linux or windows?

**Comment by szagi3891** [comment] 2015-10-14 12:55
x86, linux (debian 8)

**Comment by zonyitoo** [comment] 2015-10-14 17:40
That's weird. Because AppVeyor indicates that `context-rs` runs well in x86 Windows. I cannot test the coio because I don't have a x86 system and `mio` has bug under Windows.

Could you please clone the [context-rs](https://github.com/zonyitoo/context-rs) and run the following commands on your system:

```
cargo test
cargo run --example simple
cargo run --example asymmetric
```

and tell me if there are any errors occur?

**Comment by szagi3891** [comment] 2015-10-14 18:34
Ok. The output :

```
grzegorz@grzegorz:~/Pulpit/rust_server$ git clone https://github.com/zonyitoo/context-rs
Cloning into 'context-rs'...
remote: Counting objects: 238, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 238 (delta 3), reused 0 (delta 0), pack-reused 225
Receiving objects: 100% (238/238), 51.20 KiB | 0 bytes/s, done.
Resolving deltas: 100% (125/125), done.
Checking connectivity... done.
grzegorz@grzegorz:~/Pulpit/rust_server$ 
grzegorz@grzegorz:~/Pulpit/rust_server$ 
grzegorz@grzegorz:~/Pulpit/rust_server$ cd context-rs/
grzegorz@grzegorz:~/Pulpit/rust_server/context-rs$ 
grzegorz@grzegorz:~/Pulpit/rust_server/context-rs$ 
grzegorz@grzegorz:~/Pulpit/rust_server/context-rs$ cargo test
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling winapi-build v0.1.1
   Compiling gcc v0.3.18
   Compiling libc v0.1.10
   Compiling log v0.3.2
   Compiling context v0.1.3 (file:///home/grzegorz/Pulpit/rust_server/context-rs)
   Compiling winapi v0.2.4
   Compiling kernel32-sys v0.1.4
   Compiling fs2 v0.1.0
   Compiling memmap v0.2.1
     Running target/debug/context-bc1a8e47dff043f3

running 4 tests
test context::test::test_load_save_context ... ok
test context::test::test_swap_context ... ok
test stack::tests::stack_pool_caches ... ok
test stack::tests::stack_pool_caches_exact ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured

   Doc-tests context

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

grzegorz@grzegorz:~/Pulpit/rust_server/context-rs$ cargo run --example simple
     Running `target/debug/examples/simple`
Before switch
Inside your function!
Back to main function
grzegorz@grzegorz:~/Pulpit/rust_server/context-rs$ cargo run --example asymmetric
     Running `target/debug/examples/asymmetric`
0
1
2
3
4
5
6
7
8
9
grzegorz@grzegorz:~/Pulpit/rust_server/context-rs$ 
```

**Comment by zonyitoo** [comment] 2015-10-14 19:40
It seems that `context-rs` works very well. So why the segmfault happens in this crate? That's pretty weird.

In this crate, run

```
cargo run --example simple
```

Is that works fine? Or it still get segmfault?

**Comment by szagi3891** [comment] 2015-10-14 19:46
the output :

grzegorz@grzegorz:~/Pulpit/rust_server/context-rs$ cargo run --example simple
     Running `target/debug/examples/simple`
Before switch
Inside your function!
Back to main function
grzegorz@grzegorz:~/Pulpit/rust_server/context-rs$ 
```

```
grzegorz@grzegorz:~/Pulpit/rust_server/coio-rs$ cargo run --example simple
   Compiling coio v0.1.3 (file:///home/grzegorz/Pulpit/rust_server/coio-rs)
     Running `target/debug/examples/simple`
Heil Hydra
Heil Hydra
Heil Hydra
Heil Hydra
Heil Hydra
Heil Hydra
Heil Hydra
Heil Hydra
Heil Hydra
Heil Hydra
grzegorz@grzegorz:~/Pulpit/rust_server/coio-rs$ 
```

**Comment by zonyitoo** [comment] 2015-10-14 20:09
Ah! it works!! So I think the problem is this line: https://github.com/zonyitoo/coio-rs/blob/master/examples/tcp-echo-server.rs#L45

I still don't know why it crash, so modified this line to be:

```rust
let (mut stream, addr) = match stream {
    Ok(s) => s,
    Err(err) => {
        error!("Failed to accept connection: {:?}", err);
        return;
    }
};
```

And see whether it will print out some error message.

**Comment by szagi3891** [comment] 2015-10-14 20:29
The output :

```

**Comment by zonyitoo** [comment] 2015-10-14 20:35
Ok, it should be a bug. I will close this issue because the problem of simd have been solved. This is another issue of segmfault on x86 Linux.

**Closed by zonyitoo** 2015-10-14 20:35 UTC

**Comment by szagi3891** [comment] 2015-10-14 20:52
You open new issue ?

**Comment by szagi3891** [comment] 2015-10-15 03:53
Thanks :)
